name: ci

on: [push, pull_request]

jobs:
  build:
    name: run test with deno version ${{ matrix.deno }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [0.40.0]
    steps:
      - name: clone repo
        uses: actions/checkout@v1
      - name: install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: run fmt
        run: deno fmt --check
      - name: run tests
        run: deno test
